## banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/vendas_db
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver

## jpa - hibernate 
## update> cria ou atualizada tabelas automaticamente com base nas entidades 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# desabilita open-in-view 
spring.jpa.open-in-view=false

## faz datas aparecerem como "2026-05-18"
spring.jackson.serialization.write-dates-as-timestamps=false

## segurança - base auth
app.security.usuario=admin
app.security.senha=admin123

## 2FA - TOTP
## segredo usado para gerar o codigo OTP (em producao, seria por usuario no banco)
app.totp.secret=DESAFIO_SECRET_VENDAS_2024

## servidor 
server.port=8080
